DROP DATABASE IF EXISTS employeeTrackerDB;
CREATE DATABASE employeeTrackerDB;

CREATE TABLE employee (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
)

CREATE TABLE employeeRole (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
)

CREATE TABLE department (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
)